title: The Raman Project
description: A wiki repository for everything related to Raman spectroscopy, machine learning, and related spectroscopic method. For use internally.
theme: just-the-docs

#url: https://just-the-docs.github.io

aux_links:
  This repository: https://github.com/Amane-Fujimiya/RamanRepoDemo

favicon_ico: "/assets/images/favicon.ico"

color_scheme: dark

#markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

#kramdown:
#  footnote_backlink: "&#8617;&#xfe0e;"
#  syntax_highlighter: rouge
#  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
#    css_class: highlight
#    # default_lang: console
#    span:
#      line_numbers: false
#    block:
#      line_numbers: true
#      start_line: 1

defaults:
  - scope:
      path: "docs"  # Applies only to files inside the "docs" folder
      type: "pages"  # Applies only to pages (not posts or other content)
    values:
      layout: "default"  # Sets the default layout for these pages to "default"

# If you have any plugins, put them here!
plugins:
  - jekyll-spaceship

# Collection supposition
collections:
  journal: 
    output: true
  raman:
    output: true

just_the_docs:
  collections:
    journal:
      name: Journal
      nav_fold: false
    raman:
      name: Theory
      nav_fold: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)


